#!/bin/bash
#
# vi: ts=2 sts=2 sw=2 ft=bash
#
# Show latest commit log for files in the specified directory like git-blame.
# Inspired by: https://stackoverflow.com/questions/34260196/how-to-git-blame-a-directory
set -u

readonly BLAME_FORMAT='%C(auto)%h (%<(20,trunc)%an %ad %<(40,trunc)%s)'
readonly PATH_COLUMNS=20

main() {
  [[ -n ${GIT_TRACE:+trace_on} ]] && set -x && trap 'set +x' EXIT ERR

  local short_path
  for f in "${1:-}"*; do
    if (( ${#f} > ${PATH_COLUMNS} )); then
      short_path="..${f: -$((PATH_COLUMNS - 2))}"
    else
      short_path="${f}"
    fi
    git log -n 1 --date=iso-local --format="${BLAME_FORMAT} ${short_path}" -- "${f}"
  done
}

main "$@"
